Feature: Generate automatically Symfony controllers
  In order to make my life easier
  As a developer
  I need to generate my controllers automatically based on specification file

  Scenario: Generate a simple controller
    Given I have "simple.raml"
    And I want to use "Foo\Bar" as namespace
    When I generate
    Then I should get "PostsController.php" file generated with given content:
      """
      <?php

      namespace Foo\Bar;

      use Symfony\Bundle\FrameworkBundle\Controller\Controller;
      use Symfony\Component\HttpFoundation\Request;
      use Symfony\Component\HttpFoundation\Response;

      use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
      use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;

      /**
       * This class has been auto-generated by Api2Symfony: https://github.com/creads/api2symfony
       */
      class PostsController extends Controller
      {
          /**
           * Get a specific coment
           *
           * @Route("/posts/{slug}/comments/{page}/{id}", name="get_posts_slug_page_id")
           * @Method({"GET"})
           */
          public function getPostsSlugPageIdAction(Request $request, $slug, $page, $id)
          {
              /* You can provide a _code query parameter to get whatever response code you want */
              /* If your api doesn't handle the requested response code, the first response available is returned */
              /* You can provide a _content_type query parameter to get whatever response content type you want */
              return new Response(
                  '',
                  ,
                  array(
                  )
              );
          }

      }

      """

